#+title: Spack packages for edep-sim + simphony

* Caveats

This is for an R&D project and not (yet) intended for production.
- [X] Provide building of [[https://github.com/ClarkMcGrew/edep-sim/][edep-sim]] and [[https://github.com/bnlnpps/simphony][simphony]] either individually or together.
- [ ] Provide building of [[https://github.com/Ningclover/edep-opticks-plugin][edep-opticks-plugin]]

* Quick start

** Prepare Spack

#+begin_example
git clone \
  -c feature.manyFiles=true --depth 1 --branch v1.1.0 \
  https://github.com/spack/spack.git /path/to/spack
#+end_example

You can either use =/path/to/spack/bin/spack= or source or start a subshell with
Spack's shell support.  Eg:

#+begin_example
bash --rcfile /path/to/spack/share/spack/setup-env.sh
#+end_example

Then, initialize Spack.

#+begin_example
spack compiler find
spack bootstrap now
#+end_example

With Spack 1.1.0 we need to use newer packaging in order to get the newer Geant4 11.4 that edep-sim needs.  This can be done with:

#+begin_example
cd $(spack repo list| awk '/builtin/ {print $NF}')
git fetch --tags
git checkout v2026.03.0
cd -
#+end_example

Confirm with:
#+begin_example
$ spack info geant4|grep 11.4.0
    11.4.0    https://gitlab.cern.ch/geant4/geant4/-/archive/v11.4.0/geant4-v11.4.0.tar.gz
#+end_example

** Prepare this Spack repo

#+begin_example
git clone https://github.com/WireCell/edep-simphony-spack.git
spack repo add edep-simphony-spack/edep_simphony/
#+end_example

** Build individual packages

#+begin_example
spack install -j 20 edepsim cxxstd=17
spack install -j 20 simphony cxxstd=17
#+end_example

** Build all together in an environment

#+begin_example
spack env create edepsimphony
spack -e edepsimphony add edepsim cxxstd=17
spack -e edepsimphony add simphony cxxstd=17
#+end_example

* Developing

This section collects some guidance to set up a developer environment.

** Create development area using a Spack Environment

This requires your shell to be "setup" for Spack.  See next for a less invasive way.

#+begin_example
  mkdir hack && cd hack/

  spack env create --with-view local -d . 
  spack env activate .
  spack add edepsim cxxstd=17
  spack add simphony cxxstd=17
  spack install
#+end_example

You now have dependencies and the two packages themselves under the view directory =local/=.  While in the shell environment for the Spack Environment you have =PKG_CONFIG_PATH= and =CMAKE_PREFIX_PATH= which will let most build systems find dependencies.

Exit the subshell or run =despacktivate= to remove the Spack shell modifications.




